#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$FasmPath = $env:FASM,
    [string]$LlvmBin = $env:LLVM_BIN
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$development = Join-Path $root 'Development'
$boot = Join-Path $development 'Boot'
. (Join-Path $root 'build-tools.ps1')
$buildTools = Get-OsBuildTools -FasmPath $FasmPath -LlvmBin $LlvmBin
$fasm = $buildTools.Fasm
$layout = Get-OsBootLayout (Join-Path $boot 'BootLayout.inc')

if (-not ('BootImageCrc32' -as [type])) {
    Add-Type -TypeDefinition @'
public static class BootImageCrc32 {
    public static uint Compute(byte[] bytes) {
        uint crc = 0xffffffff;
        foreach (byte value in bytes) {
            crc ^= value;
            for (int bit = 0; bit < 8; ++bit)
                crc = (crc >> 1) ^ ((crc & 1) != 0 ? 0xedb88320u : 0u);
        }
        return ~crc;
    }
}
'@
}
function Get-PayloadCrc([string]$name, [int]$sectors) {
    $bytes = [IO.File]::ReadAllBytes((Join-Path $development $name))
    if ($bytes.Length -gt $sectors * 512) { throw "$name exceeds its sector reservation" }
    $padded = New-Object byte[] ($sectors * 512)
    [Array]::Copy($bytes, $padded, $bytes.Length)
    return [BootImageCrc32]::Compute($padded)
}
$highCrc = Get-PayloadCrc 'Arch\x86\VirtualKernel.bin' $layout.HIGH_SECTORS
$interruptCrc = Get-PayloadCrc 'Arch\x86\InterruptHandlers.bin' $layout.INT_SECTORS
$manifest = @"
; Generated by build-bootstrap.ps1 from the actual padded payloads. Do not edit.
dd 04253554Eh, 0544F4F42h
dd 1, SETUP_SECTORS
dd HIGH_START_LBA, HIGH_SECTORS, 0x$($highCrc.ToString('X8'))
dd INT_START_LBA, INT_SECTORS, 0x$($interruptCrc.ToString('X8'))
"@
[IO.File]::WriteAllText((Join-Path $boot 'BootManifest.inc'), $manifest, [Text.Encoding]::ASCII)

& $buildTools.Clang --target=i386-unknown-none-elf -march=pentium-m -std=c11 -Os `
    -Wall -Wextra -Werror -ffreestanding -fno-builtin -fno-pic -fno-pie `
    -fno-stack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables `
    -fno-omit-frame-pointer -ffunction-sections -fdata-sections `
    -mno-sse -mno-sse2 -mno-mmx -msoft-float -I $development `
    -c "$boot\BootStorage.c" -o "$boot\BootStorage.o"
if ($LASTEXITCODE -ne 0) { throw 'Native boot storage compilation failed' }
& $buildTools.Linker -m elf_i386 -T "$boot\boot-storage.ld" --gc-sections `
    -nostdlib -o "$boot\BootStorage.elf" "$boot\BootStorage.o"
if ($LASTEXITCODE -ne 0) { throw 'Native boot storage link failed' }
& $buildTools.Objcopy -O binary "$boot\BootStorage.elf" "$boot\BootStorage.bin"
if ($LASTEXITCODE -ne 0) { throw 'Native boot storage binary conversion failed' }
Push-Location $root
try {
    & $fasm "$development\Boot\kernel.asm" "$development\Boot\kernel.bin"
    if ($LASTEXITCODE -ne 0) { throw 'Bootstrap assembly failed' }
    & $fasm "$development\Boot\bl.asm" "$development\Boot\bl.bin"
    if ($LASTEXITCODE -ne 0) { throw 'Boot sector assembly failed' }
} finally { Pop-Location }
Write-Host "Native loader: $((Get-Item "$boot\BootStorage.bin").Length) bytes"
Write-Host "Bootstrap:    $((Get-Item "$development\Boot\kernel.bin").Length) bytes (64 sectors)"
Write-Host "Payload CRCs: $($highCrc.ToString('X8')) / $($interruptCrc.ToString('X8'))"
